### ISSUE TITLE
Create  community forum page

### ISSUE THREAD

**Issue by anjali-001** [anjali-001/indie-threads#14]

**Comment by SiddeshSambasivam** [comment]
## **Database Schema**

**Collection: posts**
Each document in the `posts` collection represents a game page that contains the discussion section and other game Infos.
1. author - string
2. title - string
3. genre - String
3. developer - string
3. description - string
4. platformsAvailable - string
5. releaseDate - timestamp or string
6. createdAt - timestamp
7. gameplayImages - array of references to the `images collection`
8. gameplayVideos - array of references to the video links (youtube)
9. comments - array of references to the comments in the `comments collection`
10. website - string

**Collection: comments**
1. gameId - string (reference to the id of the game document in the posts)
2. createdAt - timestamp
2. text - string
3. replyTo - reference to the root comment if it is a reply

**Comment by SiddeshSambasivam** [comment]
**Progress made:**

1. Setup the UI components for the page
2. Added theme to the scrollbar
